#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "${SCRIPT_DIR}/../.." && pwd)"

run_cmd() {
  local label="$1"
  shift
  echo "[prepare] ${label}: $*"
  "$@"
}

ensure_tool() {
  local name="$1"
  if ! command -v "$name" >/dev/null 2>&1; then
    echo "[prepare] missing required tool: $name" >&2
    exit 1
  fi
}

prepare_go_case() {
  local module="$1"
  local version="$2"
  if [[ -z "$module" || -z "$version" ]]; then
    return
  fi
  run_cmd "go download" go mod download "${module}@${version}"
}

prepare_rust_case() {
  local package="$1"
  local version="$2"
  if [[ -z "$package" || -z "$version" ]]; then
    return
  fi
  local tmp_dir
  tmp_dir="$(mktemp -d /tmp/cogna-remote-rust-XXXXXX)"
  trap 'rm -rf "${tmp_dir}"' RETURN
  cat >"${tmp_dir}/Cargo.toml" <<EOF
[package]
name = "cogna-remote-e2e-prewarm"
version = "0.0.0"
edition = "2021"

[lib]
path = "lib.rs"

[dependencies]
${package} = "=${version}"
EOF
  : >"${tmp_dir}/lib.rs"
  cat >"${tmp_dir}/Cargo.lock" <<EOF
# This file is automatically @generated by Cargo.
version = 3
EOF
  run_cmd "cargo fetch ${package}@${version}" cargo fetch --manifest-path "${tmp_dir}/Cargo.toml"
  trap - RETURN
  rm -rf "${tmp_dir}"
}

prepare_terraform_case() {
  local kind="$1"
  local source="$2"
  local version="$3"
  if [[ "$kind" != "module" && "$kind" != "provider" ]]; then
    return
  fi
  if [[ -z "$source" ]]; then
    return
  fi
  local tf_root
  tf_root="${COGNA_REMOTE_WORKSPACE_ROOT:-${REPO_ROOT}/.tmp/remote-e2e-workspace}"
  mkdir -p "${tf_root}"
  local tf_file
  tf_file="${tf_root}/main.tf"
  if [[ "$kind" == "module" ]]; then
    cat >"${tf_file}" <<EOF
module "remote_e2e" {
  source = "${source}"
$(if [[ -n "$version" ]]; then printf '  version = "%s"\n' "$version"; fi)
}
EOF
  else
    cat >"${tf_file}" <<EOF
terraform {
  required_providers {
    remote_e2e = {
      source = "${source}"
$(if [[ -n "$version" ]]; then printf '      version = "%s"\n' "$version"; fi)
    }
  }
}
EOF
  fi
  run_cmd "terraform init (${kind}:${source})" terraform -chdir="${tf_root}" init -upgrade -no-color
}

parse_cases() {
  local manifest="$1"
  local kind="$2"
  python3 - "$manifest" "$kind" <<'PY'
import json
import sys

manifest = sys.argv[1]
kind = sys.argv[2]

with open(manifest, "r", encoding="utf-8") as handle:
    data = json.load(handle)

for case in data.get("cases", []):
    if kind == "go":
        module = (case.get("module") or "").strip()
        version = (case.get("version") or "").strip()
        if module and version:
            print(f"{module}\t{version}")
    elif kind == "rust":
        package = (case.get("package") or "").strip()
        version = (case.get("version") or "").strip()
        if package and version:
            print(f"{package}\t{version}")
    elif kind == "terraform":
        tf_kind = (case.get("terraform_kind") or "").strip()
        source = (case.get("source") or "").strip()
        version = (case.get("version") or "").strip()
        if tf_kind and source:
            print(f"{tf_kind}\t{source}\t{version}")
PY
}

main() {
  ensure_tool python3
  ensure_tool go
  ensure_tool cargo
  ensure_tool terraform

  export COGNA_REMOTE_WORKSPACE_ROOT="${COGNA_REMOTE_WORKSPACE_ROOT:-${REPO_ROOT}/.tmp/remote-e2e-workspace}"

  local go_manifest="${REPO_ROOT}/e2e/extractors/go-remote.json"
  local rust_manifest="${REPO_ROOT}/e2e/extractors/rust.json"
  local terraform_manifest="${REPO_ROOT}/e2e/extractors/terraform-remote.json"

  while IFS=$'\t' read -r module version; do
    [[ -z "${module}" ]] && continue
    prepare_go_case "$module" "$version"
  done < <(parse_cases "${go_manifest}" go)

  while IFS=$'\t' read -r package version; do
    [[ -z "${package}" ]] && continue
    prepare_rust_case "$package" "$version"
  done < <(parse_cases "${rust_manifest}" rust)

  while IFS=$'\t' read -r tf_kind tf_source tf_version; do
    [[ -z "${tf_kind}" ]] && continue
    prepare_terraform_case "$tf_kind" "$tf_source" "$tf_version"
  done < <(parse_cases "${terraform_manifest}" terraform)

  echo "[prepare] remote e2e dependency prewarm completed"
}

main "$@"
