package emitter

import (
	"fmt"
	"path"
	"sort"
	"strings"

	"github.com/cogna-dev/cogna/tools/protoc-gen-cogna/internal/ir"
)

func EmitTypeScript(file *ir.File, version string) (string, string) {
	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("// Code generated by protoc-gen-cogna %s. DO NOT EDIT.\n", version))
	sb.WriteString(fmt.Sprintf("// Source: %s\n\n", file.ProtoPath))

	writeTypeScriptImports(&sb, file)
	writeTypeScriptHelpers(&sb)

	for _, enum := range file.Enums {
		writeTypeScriptEnum(&sb, enum)
	}

	for _, message := range file.Messages {
		writeTypeScriptOneofs(&sb, message)
		writeTypeScriptMessage(&sb, message)
	}

	filename := path.Join("node/src/generated", file.TsModule+".ts")
	return filename, sb.String()
}

func writeTypeScriptImports(sb *strings.Builder, file *ir.File) {
	imports := map[string][]string{}
	needsTypes := true
	for _, message := range file.Messages {
		for _, field := range message.Fields {
			collectTypeScriptImports(imports, field)
			if field.Kind == ir.KindEnum {
				needsTypes = true
			}
			if field.Kind == ir.KindAny || field.Kind == ir.KindNullValue {
				needsTypes = true
			}
		}
		for _, oneof := range message.Oneofs {
			for _, field := range oneof.Fields {
				collectTypeScriptImports(imports, field)
				if field.Kind == ir.KindEnum {
					needsTypes = true
				}
				if field.Kind == ir.KindAny || field.Kind == ir.KindNullValue {
					needsTypes = true
				}
			}
		}
	}
	if needsTypes {
		sb.WriteString("import type { JsonObject, JsonValue } from '../types'\n")
	}
	paths := make([]string, 0, len(imports))
	for importPath := range imports {
		paths = append(paths, importPath)
	}
	sort.Strings(paths)
	for _, importPath := range paths {
		types := imports[importPath]
		sort.Strings(types)
		sb.WriteString(fmt.Sprintf("import { %s } from './%s.js'\n", strings.Join(types, ", "), importPath))
	}
	if needsTypes || len(paths) > 0 {
		sb.WriteString("\n")
	}
}

func collectTypeScriptImports(imports map[string][]string, field *ir.FieldDef) {
	if field.Kind == ir.KindMap {
		if field.Map == nil || field.Map.ValueTypeModule == "" {
			return
		}
		addTypeScriptImport(imports, field.Map.ValueTypeModule, field.Map.ValueTypeName, field.Map.ValueKind)
		return
	}
	if field.TypeModule == "" {
		return
	}
	addTypeScriptImport(imports, field.TypeModule, field.TypeName, field.Kind)
}

func addTypeScriptImport(imports map[string][]string, module string, typeName string, kind ir.FieldKind) {
	moduleName := strings.TrimSuffix(path.Base(module), ".proto")
	addTypeScriptImportName(imports, moduleName, typeName)
	switch kind {
	case ir.KindEnum:
		addTypeScriptImportName(imports, moduleName, lowerFirst(typeName)+"Values")
	case ir.KindMessage:
		addTypeScriptImportName(imports, moduleName, "parse"+typeName)
		addTypeScriptImportName(imports, moduleName, "serialize"+typeName)
	}
}

func addTypeScriptImportName(imports map[string][]string, moduleName string, name string) {
	for _, existing := range imports[moduleName] {
		if existing == name {
			return
		}
	}
	imports[moduleName] = append(imports[moduleName], name)
}

func writeTypeScriptEnum(sb *strings.Builder, enum *ir.EnumDef) {
	sb.WriteString(fmt.Sprintf("export type %s =\n", enum.Name))
	for index, value := range enum.Values {
		prefix := " |"
		if index == 0 {
			prefix = "  "
		}
		sb.WriteString(fmt.Sprintf("%s '%s'\n", prefix, value.Name))
	}
	sb.WriteString("\n")
	sb.WriteString(fmt.Sprintf("export const %sValues: Record<%s, number> = {\n", lowerFirst(enum.Name), enum.Name))
	for _, value := range enum.Values {
		sb.WriteString(fmt.Sprintf("  '%s': %d,\n", value.Name, value.Number))
	}
	sb.WriteString("} as const\n\n")
}

func writeTypeScriptOneofs(sb *strings.Builder, message *ir.MessageDef) {
	for _, oneof := range message.Oneofs {
		typeName := message.Name + upperCamel(oneof.Name)
		sb.WriteString(fmt.Sprintf("export type %s =\n", typeName))
		for index, field := range oneof.Fields {
			prefix := " |"
			if index == 0 {
				prefix = "  "
			}
			sb.WriteString(fmt.Sprintf("%s { case: '%s'; value: %s }\n", prefix, field.JSONName, typeScriptOneofFieldType(field)))
		}
		sb.WriteString("\n")
		writeTypeScriptOneofParsers(sb, message, oneof)
	}
}

func writeTypeScriptOneofParsers(sb *strings.Builder, message *ir.MessageDef, oneof *ir.OneofDef) {
	typeName := message.Name + upperCamel(oneof.Name)
	sb.WriteString(fmt.Sprintf("export function parse%s(raw: unknown): %s | undefined {\n", typeName, typeName))
	sb.WriteString("  if (!isRecord(raw)) {\n    return undefined\n  }\n")
	for _, field := range oneof.Fields {
		sb.WriteString(fmt.Sprintf("  if (raw['%s'] !== undefined) {\n", field.JSONName))
		sb.WriteString(fmt.Sprintf("    const value = %s\n", typeScriptParseValueExpr(fmt.Sprintf("raw['%s']", field.JSONName), field, true)))
		sb.WriteString("    if (value === undefined) {\n      return undefined\n    }\n")
		sb.WriteString(fmt.Sprintf("    return { case: '%s', value }\n", field.JSONName))
		sb.WriteString("  }\n")
	}
	sb.WriteString("  return undefined\n")
	sb.WriteString("}\n\n")

	sb.WriteString(fmt.Sprintf("export function serialize%s(value: %s | undefined): Record<string, unknown> | undefined {\n", typeName, typeName))
	sb.WriteString("  if (value === undefined) {\n    return undefined\n  }\n")
	sb.WriteString("  switch (value.case) {\n")
	for _, field := range oneof.Fields {
		sb.WriteString(fmt.Sprintf("    case '%s':\n", field.JSONName))
		sb.WriteString(fmt.Sprintf("      return { '%s': %s }\n", field.JSONName, typeScriptSerializeValueExpr("value.value", field, true)))
	}
	sb.WriteString("  }\n")
	sb.WriteString("}\n\n")
}

func writeTypeScriptMessage(sb *strings.Builder, message *ir.MessageDef) {
	sb.WriteString(fmt.Sprintf("export interface %s {\n", message.Name))
	for _, field := range message.Fields {
		optional := ""
		if field.Optional {
			optional = "?"
		}
		sb.WriteString(fmt.Sprintf("  %s%s: %s\n", field.JSONName, optional, typeScriptFieldType(field)))
	}
	for _, oneof := range message.Oneofs {
		sb.WriteString(fmt.Sprintf("  %s?: %s\n", oneof.TsName, message.Name+upperCamel(oneof.Name)))
	}
	sb.WriteString("}\n\n")

	sb.WriteString(fmt.Sprintf("export function parse%s(raw: unknown): %s {\n", message.Name, message.Name))
	sb.WriteString("  const o = ensureRecord(raw)\n")
	sb.WriteString("  return {\n")
	for _, field := range message.Fields {
		sb.WriteString(fmt.Sprintf("    %s: %s,\n", field.JSONName, typeScriptParseFieldExpr(field)))
	}
	for _, oneof := range message.Oneofs {
		sb.WriteString(fmt.Sprintf("    %s: parse%s(o),\n", oneof.TsName, message.Name+upperCamel(oneof.Name)))
	}
	sb.WriteString("  }\n")
	sb.WriteString("}\n\n")

	sb.WriteString(fmt.Sprintf("export function serialize%s(value: %s): Record<string, unknown> {\n", message.Name, message.Name))
	sb.WriteString("  const out: Record<string, unknown> = {}\n")
	for _, field := range message.Fields {
		writeTypeScriptSerializeField(sb, field)
	}
	for _, oneof := range message.Oneofs {
		sb.WriteString(fmt.Sprintf("  const %s = serialize%s(value.%s)\n", oneof.TsName, message.Name+upperCamel(oneof.Name), oneof.TsName))
		sb.WriteString(fmt.Sprintf("  if (%s !== undefined) {\n    Object.assign(out, %s)\n  }\n", oneof.TsName, oneof.TsName))
	}
	sb.WriteString("  return out\n")
	sb.WriteString("}\n\n")
}

func writeTypeScriptSerializeField(sb *strings.Builder, field *ir.FieldDef) {
	valueExpr := fmt.Sprintf("value.%s", field.JSONName)
	if field.Optional {
		sb.WriteString(fmt.Sprintf("  if (%s !== undefined) {\n", valueExpr))
		sb.WriteString(fmt.Sprintf("    out['%s'] = %s\n", field.JSONName, typeScriptSerializeValueExpr(valueExpr, field, false)))
		sb.WriteString("  }\n")
		return
	}
	sb.WriteString(fmt.Sprintf("  out['%s'] = %s\n", field.JSONName, typeScriptSerializeValueExpr(valueExpr, field, false)))
}

func typeScriptParseFieldExpr(field *ir.FieldDef) string {
	valueExpr := fmt.Sprintf("o['%s']", field.JSONName)
	if field.Repeated {
		base := *field
		base.Repeated = false
		itemType := typeScriptFieldType(&base)
		parseItem := typeScriptParseValueExpr("item", &base, true)
		return fmt.Sprintf("Array.isArray(%s) ? (%s as unknown[]).map((item) => %s).filter((item): item is %s => item !== undefined) : []", valueExpr, valueExpr, parseItem, itemType)
	}
	if field.Optional {
		return fmt.Sprintf("%s !== undefined ? %s : undefined", valueExpr, typeScriptParseValueExpr(valueExpr, field, false))
	}
	return typeScriptParseValueExpr(valueExpr, field, false)
}

func typeScriptParseValueExpr(expr string, field *ir.FieldDef, allowUndefined bool) string {
	switch field.Kind {
	case ir.KindString:
		return typeGuard(expr, "string", allowUndefined, "string")
	case ir.KindBool:
		return typeGuard(expr, "boolean", allowUndefined, "boolean")
	case ir.KindInt32, ir.KindUInt32:
		return typeScriptNumberExpr(expr, allowUndefined, true)
	case ir.KindInt64, ir.KindUInt64, ir.KindFloat, ir.KindDouble:
		return typeScriptNumberExpr(expr, allowUndefined, false)
	case ir.KindBytes:
		return fmt.Sprintf("typeof %s === 'string' ? decodeBytes(%s) : %s", expr, expr, undefinedOrDefault(allowUndefined, "new Uint8Array()"))
	case ir.KindEnum:
		return fmt.Sprintf("typeof %s === 'string' ? (%s as %s) : %s", expr, expr, field.TypeName, undefinedOrDefault(allowUndefined, firstEnumFallback(field.TypeName)))
	case ir.KindMessage:
		return fmt.Sprintf("isRecord(%s) ? parse%s(%s) : %s", expr, field.TypeName, expr, undefinedOrDefault(allowUndefined, fmt.Sprintf("parse%s({})", field.TypeName)))
	case ir.KindAny:
		return fmt.Sprintf("isJsonValue(%s) ? %s : %s", expr, expr, undefinedOrDefault(allowUndefined, "{}"))
	case ir.KindNullValue:
		return fmt.Sprintf("%s === null ? null : %s", expr, undefinedOrDefault(allowUndefined, "null"))
	case ir.KindMap:
		return typeScriptParseMapExpr(expr, field.Map, allowUndefined)
	default:
		return undefinedOrDefault(allowUndefined, "undefined")
	}
}

func typeScriptSerializeValueExpr(expr string, field *ir.FieldDef, oneof bool) string {
	if field.Repeated && !oneof {
		base := *field
		base.Repeated = false
		return fmt.Sprintf("%s.map((item) => %s)", expr, typeScriptSerializeValueExpr("item", &base, false))
	}
	if field.Kind == ir.KindMap {
		return typeScriptSerializeMapExpr(expr, field.Map)
	}
	switch field.Kind {
	case ir.KindBytes:
		return fmt.Sprintf("encodeBytes(%s)", expr)
	case ir.KindMessage:
		return fmt.Sprintf("serialize%s(%s)", field.TypeName, expr)
	default:
		return expr
	}
}

func typeScriptParseMapExpr(expr string, mapping *ir.MapDef, allowUndefined bool) string {
	if mapping == nil {
		return undefinedOrDefault(allowUndefined, "{}")
	}
	field := &ir.FieldDef{Kind: mapping.ValueKind, TypeName: mapping.ValueTypeName, TypeModule: mapping.ValueTypeModule}
	fallback := undefinedOrDefault(allowUndefined, "{}")
	return fmt.Sprintf("isRecord(%s) ? Object.fromEntries(Object.entries(%s).map(([key, value]) => [key, %s]).filter((entry): entry is [string, %s] => entry[1] !== undefined)) : %s", expr, expr, typeScriptParseValueExpr("value", field, true), typeScriptFieldType(field), fallback)
}

func typeScriptSerializeMapExpr(expr string, mapping *ir.MapDef) string {
	if mapping == nil {
		return expr
	}
	field := &ir.FieldDef{Kind: mapping.ValueKind, TypeName: mapping.ValueTypeName, TypeModule: mapping.ValueTypeModule}
	return fmt.Sprintf("Object.fromEntries(Object.entries(%s).map(([key, value]) => [key, %s]))", expr, typeScriptSerializeValueExpr("value", field, false))
}

func typeScriptFieldType(field *ir.FieldDef) string {
	base := typeScriptBaseType(field)
	if field.Repeated {
		base += "[]"
	}
	if field.Optional {
		return base + " | undefined"
	}
	return base
}

func typeScriptOneofFieldType(field *ir.FieldDef) string {
	base := typeScriptBaseType(field)
	if field.Repeated {
		base += "[]"
	}
	return base
}

func typeScriptBaseType(field *ir.FieldDef) string {
	switch field.Kind {
	case ir.KindString:
		return "string"
	case ir.KindBool:
		return "boolean"
	case ir.KindInt32, ir.KindUInt32, ir.KindFloat, ir.KindDouble:
		return "number"
	case ir.KindInt64, ir.KindUInt64:
		return "number"
	case ir.KindBytes:
		return "Uint8Array"
	case ir.KindEnum, ir.KindMessage:
		return field.TypeName
	case ir.KindAny:
		return "JsonValue | JsonObject"
	case ir.KindNullValue:
		return "null"
	case ir.KindMap:
		return fmt.Sprintf("Record<string, %s>", typeScriptMapValueType(field.Map))
	default:
		return "unknown"
	}
}

func typeScriptMapValueType(mapping *ir.MapDef) string {
	if mapping == nil {
		return "unknown"
	}
	field := &ir.FieldDef{Kind: mapping.ValueKind, TypeName: mapping.ValueTypeName, TypeModule: mapping.ValueTypeModule}
	return typeScriptBaseType(field)
}

func typeScriptDefaultExpr(field *ir.FieldDef) string {
	switch field.Kind {
	case ir.KindString:
		return "''"
	case ir.KindBool:
		return "false"
	case ir.KindInt32, ir.KindUInt32, ir.KindInt64, ir.KindUInt64, ir.KindFloat, ir.KindDouble:
		return "0"
	case ir.KindBytes:
		return "new Uint8Array()"
	case ir.KindEnum:
		return firstEnumFallback(field.TypeName)
	case ir.KindMessage:
		return fmt.Sprintf("parse%s({})", field.TypeName)
	case ir.KindAny:
		return "{}"
	case ir.KindNullValue:
		return "null"
	case ir.KindMap:
		return "{}"
	default:
		return "undefined"
	}
}

func typeScriptNumberExpr(expr string, allowUndefined bool, truncate bool) string {
	base := expr
	if truncate {
		base = fmt.Sprintf("(%s | 0)", expr)
	}
	return fmt.Sprintf("typeof %s === 'number' ? %s : %s", expr, base, undefinedOrDefault(allowUndefined, "0"))
}

func typeGuard(expr string, want string, allowUndefined bool, output string) string {
	return fmt.Sprintf("typeof %s === '%s' ? %s : %s", expr, want, expr, undefinedOrDefault(allowUndefined, outputDefault(output)))
}

func outputDefault(output string) string {
	switch output {
	case "string":
		return "''"
	case "boolean":
		return "false"
	default:
		return "undefined"
	}
}

func undefinedOrDefault(allowUndefined bool, fallback string) string {
	if allowUndefined {
		return "undefined"
	}
	return fallback
}

func firstEnumFallback(typeName string) string {
	return fmt.Sprintf("(%sValues ? Object.keys(%sValues)[0] : undefined) as %s", lowerFirst(typeName), lowerFirst(typeName), typeName)
}

func lowerFirst(value string) string {
	if value == "" {
		return value
	}
	return strings.ToLower(value[:1]) + value[1:]
}

func upperCamel(value string) string {
	parts := strings.Split(value, "_")
	var out strings.Builder
	for _, part := range parts {
		if part == "" {
			continue
		}
		out.WriteString(strings.ToUpper(part[:1]))
		if len(part) > 1 {
			out.WriteString(part[1:])
		}
	}
	return out.String()
}

func writeTypeScriptHelpers(sb *strings.Builder) {
	sb.WriteString(`function ensureRecord(raw: unknown): Record<string, unknown> {
  if (isRecord(raw)) {
    return raw
  }
  return {}
}

function isRecord(raw: unknown): raw is Record<string, unknown> {
  return typeof raw === 'object' && raw !== null && !Array.isArray(raw)
}

function isJsonValue(raw: unknown): raw is JsonValue | JsonObject {
  if (raw === null) {
    return true
  }
  switch (typeof raw) {
    case 'string':
    case 'number':
    case 'boolean':
      return true
    case 'object':
      if (Array.isArray(raw)) {
        return raw.every((item) => isJsonValue(item))
      }
      return Object.values(raw).every((item) => item === undefined || isJsonValue(item))
    default:
      return false
  }
}

function encodeBytes(value: Uint8Array): string {
  let out = ''
  for (const byte of value) {
    const keep =
      (byte >= 0x61 && byte <= 0x7a) ||
      (byte >= 0x41 && byte <= 0x5a) ||
      (byte >= 0x30 && byte <= 0x39) ||
      byte === 0x2d ||
      byte === 0x5f ||
      byte === 0x2e ||
      byte === 0x7e
    out += keep ? String.fromCharCode(byte) : '%' + byte.toString(16).toUpperCase().padStart(2, '0')
  }
  return out
}

function decodeBytes(value: string): Uint8Array {
  const out: number[] = []
  for (let i = 0; i < value.length; ) {
    if (value[i] === '%') {
      if (i + 2 >= value.length) {
        return new Uint8Array()
      }
      const next = Number.parseInt(value.slice(i + 1, i + 3), 16)
      if (Number.isNaN(next)) {
        return new Uint8Array()
      }
      out.push(next)
      i += 3
      continue
    }
    out.push(value.charCodeAt(i) & 0xff)
    i += 1
  }
  return Uint8Array.from(out)
}

`)
}
